### ISSUE TITLE
Blacklist.txt generator?

### ISSUE THREAD

**Issue by okiyama** [WildBanjos/DiffusionDefender#1]
Howdy!

I think a great feature would be some kind of little walkthrough (in a browser?) that lets you choose what content you find objectionable to help build an initial blacklist.txt.

Lemme know if you'd want help, but no guarantees!

**Comment by WildBanjos** [comment]
Hey. Hmm, I'll have to think on this. My primary concern is I don't want to be too involved in helping create lists, mainly to avoid claims of censorship, unintentionally biasing blacklists, or missing important terms.

I do have some ideas on how to help admins analyze prompt terms from historical generations. I'm thinking having some text frequency analysis which compiles every so often may help admins find good terms. (At a minimum, I may add dumping of all prompts into a CSV file so admins can at least use a spreadsheet).

In the meantime, I'm thinking adding to the readme some example lists I see across the web. They wouldn't be comprehensive, but it may be a start.

**Comment by WildBanjos** [comment]
I've added a few links to the [readme](https://github.com/WildBanjos/DiffusionDefender/blob/beta/README.md) in the beta branch. Feel free to suggest other lists and I can add them, or make a fork/pr to the beta Readme. 

Currently though, I'm not planning to include any default lists due to concerns about legal responsibility. I still have another tool in the works to help admins analyze prompts

**Comment by okiyama** [comment]
This helps a ton and makes it so I now plan to use the extension!

I get what you're saying about morality and legality. Definitely many grey
areas with all of this. Feel free to close this!

**Comment by WildBanjos** [comment]
Thanks for understanding. Links to sample lists added with #2. Feel free to add more links to sample wordlists with either an issue or a PR.
